### ISSUE TITLE
Is it possible to override some of the rules?

### ISSUE THREAD

**Issue by securisec** [jorgegonzalez/zoe#82] opened 2018-12-31 04:38 UTC
I personally like using `'` instead of `"` for strings, so is it possible to use that behaviour in the .eslintrc file? I added this rule, but seems like it is ignored by zoe

```
"rules": {
		"quotes": [
			"error", "double"
		]
	}
```

**Comment by jorgegonzalez** [comment] 2019-01-06 16:58
Not presently, but I will accept a PR adding the ability to override rules.

**Comment by jorgegonzalez** [comment] 2019-01-06 20:47
Now that I think about it, setting "singglQuotes" in a .prettierrc or .editorconfig *should* override zoe.

**Comment by Bomret** [comment] 2019-01-07 13:56
It doesn't. We just checked out zoe for our team and it still complains about missing semicolons or single quotes.

**Comment by jorgegonzalez** [comment] 2019-01-07 18:02
Let me investigate tonight.

**Comment by jorgegonzalez** [comment] 2019-02-02 15:50
Hey I think I fixed those issues. I'd love if you could give Zoe another chance.

**Comment by soulchainer** [comment] 2019-02-22 19:14
Hey!
I was checking your package yesterday, @jorgegonzalez (you're aware of it xD) and it happens that just then I solved it just overriding the rule in `.prettierrc`:

```json
{
  "singleQuote": true
}
```

So... Did you check it, @Bomret? Because, for me, it works. Maybe this issue could be, finally, closed.

**Comment by jorgegonzalez** [comment] 2019-02-23 17:05
I thought this was working but it's still not ... need to investigate.

**Comment by jorgegonzalez** [comment] 2019-02-23 18:05
I published `zoe@1.25.1`, and hopefully this is finally fixed. It was previously possible to override style rules in a `.prettierrc`, but not regular ESLint rules. Hopefully this is resolved now, @soulchainer do take a look when you are able to.

**Comment by soulchainer** [comment] 2019-02-23 19:31
No prob :).

First, one thing, about the first comment in this issue, by @securisec. The rule added in that comment is a rule for ESLint to throw an error on single quotes usage (it forces double quotes, whenever possible). Just the opposite of which was (according to the comment) desired to achieve. See ESLint documentation about [quotes rule](https://eslint.org/docs/rules/quotes).

That being said... @jorgegonzalez I'm afraid the build was somewhat broken.

Now, I get this when I try to lint with `zoe`:

```
20:16 $ yarn run lint
yarn run v1.13.0
$ zoe
/usr/bin/env: «node\r»: No existe el fichero o el directorio
error Command failed with exit code 127.
```

I tried several times, remove `node_modules`, clean cache with `yarn cache clean`... the same result. So I guess is from the build.

I know where the problem is.
After installed, if I check `vim node_modules/.bin/zoe`, the executable looks like this:

```
  1 #!/usr/bin/env node^M
  2 "use strict";^M
  3 var __importDefault = (this && this.__importDefault) || function (mod) {^M
  4     return (mod && mod.__esModule) ? mod : { "default": mod };^M
  5 };^M
  6 Object.defineProperty(exports, "__esModule", { value: true });^M
  7 const chalk_1 = __importDefault(require("chalk"));^M
  8 var ver = process.versions.node;^M
  9 var majorVer = parseInt(ver.split('.')[0], 10);^M
 10 if (majorVer < 8) {^M
 11     chalk_1.default.red(`You are running Node ${ver}.
 12         Zoe requires Node 8 or higher.
 13         Please update your version of Node.`);^M
 14     process.exit(1);^M
 15 }^M
 16 else {^M
 17     require('v8-compile-cache');^M
 18     require('./zoe');^M
 19 }^M
```

Well: all that invisible characters, `^M`, are breaking the binary and render it unusable ^_^U.
And it only happens with this package, so. It looks like, IDK, this was edited, maybe, in a Windows machine or with a wrong config, because there are all these carriage returns `\n` which are breaking the package.

**Comment by soulchainer** [comment] 2019-02-23 19:45
In the meantime, checking this specific issue (manually patching the mentioned file in my machine), I can say that if I use in my `.eslintrc`:

```
{
	"extends": "zoe/typescript",
	"rules": {
		"quotes": [
			"error", "double"
		]
	}
}
```

Which ask for `quotes` to be, preferibly `"double"` and warn with `error` when it founds otherwise (and nor the other way around), it founds a bunch of errors in my code (cause I also prefer single quotes):

```
   ✖   3:24  Replace 'react' with "react"                                                    prettier/prettier
  ✖   6:27  Strings must use doublequote.                                                   quotes
  BLAH BLAH BLAH
```

There I'm using Zoe default prettier, for you to see both warnings.
While if I set it to `single` quotes instead, just in `.eslintrc`:

```
"rules": {
		"quotes": [
			"error", "single"
		]
	}
```

It lints properly. So I guess it's fine.

Anyways, what I already said: package is unusable on install now, because the faulty generation of the `zoe` executable.

**Comment by jorgegonzalez** [comment] 2019-02-23 20:18
Sorry, my Mac is bust and this was my first time publishing on Windows https://github.com/npm/npm/issues/12371

Hopefully fixed in `1.25.3`

**Comment by soulchainer** [comment] 2019-02-23 20:27
Yes, it works now, @jorgegonzalez ! :D.

Now, as I said:

- ESLint specific rules in `.eslintrc` → works
- `.prettierrc` rules → works
- Ditch `.prettierrc` and have their rules also in `eslintrc` like

```
{
	"extends": "zoe/typescript",
	"rules": {
		"prettier/prettier": ["error", { "singleQuote": true }]
	}
}
```

Also works. :+1: .

**Comment by jorgegonzalez** [comment] 2019-02-23 20:31
Prettier reads from `.editorconfig` so those should work too.

**Comment by soulchainer** [comment] 2019-02-23 21:16
I don't use `.editorconfig`, but I tried (with no `.prettierrc` neither `.eslintrc` rules) and it seems it doesn't work.

I mean, I checked `prettier` documentation and [here](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options) it says the rules `prettier` supports via `.editorconfig` and I tried with this file (I had it around, from other project, just edit it a bit) →

```
# top-most EditorConfig file
root = true
# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8
insert_final_newline = true
trim_trailing_whitespace = true

[*.{ts,tsx}]
charset = utf-8
indent_style = space
indent_size = 8
```

At the root of my project, disabled VSCode integration with `.editorconfig` (because, if not, it formats automatically, autodetecting this file) and it doesn't work. I execute `yarn run lint` (script to `zoe`) and it just lints using the default rules and ignores the `indent_size` or anything inside the `.editorconfig`, it doesn't throw any prettier warnings related with that.

**Comment by jorgegonzalez** [comment] 2019-02-23 21:58
Hmmm it seems to work for me.

**Comment by soulchainer** [comment] 2019-02-24 00:03
IDK. As I said, I don't use `.editorconfig`, so maybe I'm missing something.

**Comment by jorgegonzalez** [comment] 2019-03-07 12:53
Going to close this for now.

**Closed by jorgegonzalez** 2019-03-07 12:53 UTC
Labels: 🏷 type: bug, 🚦 status: needs more info, 🚦 status: work in progress
